-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dft_Loop_VITIS_LOOP_23_2_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read18 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read19 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read20 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read21 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read22 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read23 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read24 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read25 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read26 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read27 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read28 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read29 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read30 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read31 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read32 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read33 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read34 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read35 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read36 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read37 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read38 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read39 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read40 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read41 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read42 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read43 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read44 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read45 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read46 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read47 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read48 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read49 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read50 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read51 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read52 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read53 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read54 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read55 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read56 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read57 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read58 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read59 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read60 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read61 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read62 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read63 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read64 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read65 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read66 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read67 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read68 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read69 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read70 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read71 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read72 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read73 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read74 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read75 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read76 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read77 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read78 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read79 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read80 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read81 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read82 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read83 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read84 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read85 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read86 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read87 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read88 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read89 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read90 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read91 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read92 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read93 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read94 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read95 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read96 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read97 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read98 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read99 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read100 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read101 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read102 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read103 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read104 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read105 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read106 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read107 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read108 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read109 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read110 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read111 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read112 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read113 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read114 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read115 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read116 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read117 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read118 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read119 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read120 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read121 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read122 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read123 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read124 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read125 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read126 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read127 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read128 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read129 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read130 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read131 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read132 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read133 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read134 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read135 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read136 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read137 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read138 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read139 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read140 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read141 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read142 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read143 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read144 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read145 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read146 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read147 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read148 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read149 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read150 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read151 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read152 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read153 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read154 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read155 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read156 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read157 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read158 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read159 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read160 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read161 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read162 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read163 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read164 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read165 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read166 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read167 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read168 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read169 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read170 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read171 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read172 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read173 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read174 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read175 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read176 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read177 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read178 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read179 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read180 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read181 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read182 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read183 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read184 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read185 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read186 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read187 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read188 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read189 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read190 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read191 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read192 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read193 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read194 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read195 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read196 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read197 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read198 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read199 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read200 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read201 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read202 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read203 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read204 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read205 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read206 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read207 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read208 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read209 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read210 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read211 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read212 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read213 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read214 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read215 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read216 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read217 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read218 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read219 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read220 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read221 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read222 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read223 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read224 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read225 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read226 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read227 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read228 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read229 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read230 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read231 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read232 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read233 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read234 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read235 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read236 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read237 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read238 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read239 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read240 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read241 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read242 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read243 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read244 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read245 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read246 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read247 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read248 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read249 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read250 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read251 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read252 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read253 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read254 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read255 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_output_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    real_output_ce0 : OUT STD_LOGIC;
    real_output_we0 : OUT STD_LOGIC;
    real_output_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    imag_output_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    imag_output_ce0 : OUT STD_LOGIC;
    imag_output_we0 : OUT STD_LOGIC;
    imag_output_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of dft_Loop_VITIS_LOOP_23_2_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_2606_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_reg_2617 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_2596_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_r_reg_2622 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_fu_2601_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_i_reg_2627 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_start : STD_LOGIC;
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_done : STD_LOGIC;
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_idle : STD_LOGIC;
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_ready : STD_LOGIC;
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_real_output_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_real_output_ce0 : STD_LOGIC;
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_real_output_we0 : STD_LOGIC;
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_real_output_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_imag_output_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_imag_output_ce0 : STD_LOGIC;
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_imag_output_we0 : STD_LOGIC;
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_imag_output_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_ce : STD_LOGIC;
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_ce : STD_LOGIC;
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2606_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2606_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2606_p_ce : STD_LOGIC;
    signal grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal grp_fu_2596_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_2596_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_2601_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_2601_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_2606_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_2606_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_2596_ce : STD_LOGIC;
    signal grp_fu_2601_ce : STD_LOGIC;
    signal grp_fu_2606_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dft_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_r : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_i : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read16 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read17 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read18 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read19 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read20 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read21 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read22 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read23 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read24 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read25 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read26 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read27 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read28 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read29 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read30 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read31 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read32 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read33 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read34 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read35 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read36 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read37 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read38 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read39 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read40 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read41 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read42 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read43 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read44 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read45 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read46 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read47 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read48 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read49 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read50 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read51 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read52 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read53 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read54 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read55 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read56 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read57 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read58 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read59 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read60 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read61 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read62 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read63 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read64 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read65 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read66 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read67 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read68 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read69 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read70 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read71 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read72 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read73 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read74 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read75 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read76 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read77 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read78 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read79 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read80 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read81 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read82 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read83 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read84 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read85 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read86 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read87 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read88 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read89 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read90 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read91 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read92 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read93 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read94 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read95 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read96 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read97 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read98 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read99 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read100 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read101 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read102 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read103 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read104 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read105 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read106 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read107 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read108 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read109 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read110 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read111 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read112 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read113 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read114 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read115 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read116 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read117 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read118 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read119 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read120 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read121 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read122 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read123 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read124 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read125 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read126 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read127 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read128 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read129 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read130 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read131 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read132 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read133 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read134 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read135 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read136 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read137 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read138 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read139 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read140 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read141 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read142 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read143 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read144 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read145 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read146 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read147 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read148 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read149 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read150 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read151 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read152 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read153 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read154 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read155 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read156 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read157 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read158 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read159 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read160 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read161 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read162 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read163 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read164 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read165 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read166 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read167 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read168 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read169 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read170 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read171 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read172 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read173 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read174 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read175 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read176 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read177 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read178 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read179 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read180 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read181 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read182 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read183 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read184 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read185 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read186 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read187 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read188 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read189 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read190 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read191 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read192 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read193 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read194 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read195 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read196 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read197 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read198 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read199 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read200 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read201 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read202 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read203 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read204 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read205 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read206 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read207 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read208 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read209 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read210 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read211 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read212 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read213 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read214 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read215 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read216 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read217 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read218 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read219 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read220 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read221 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read222 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read223 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read224 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read225 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read226 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read227 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read228 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read229 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read230 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read231 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read232 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read233 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read234 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read235 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read236 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read237 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read238 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read239 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read240 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read241 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read242 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read243 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read244 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read245 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read246 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read247 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read248 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read249 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read250 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read251 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read252 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read253 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read254 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read255 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_output_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        real_output_ce0 : OUT STD_LOGIC;
        real_output_we0 : OUT STD_LOGIC;
        real_output_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        imag_output_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        imag_output_ce0 : OUT STD_LOGIC;
        imag_output_we0 : OUT STD_LOGIC;
        imag_output_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_2596_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_2596_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_2596_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_2596_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_2596_p_ce : OUT STD_LOGIC;
        grp_fu_2601_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_2601_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_2601_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_2601_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_2601_p_ce : OUT STD_LOGIC;
        grp_fu_2606_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_2606_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_2606_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_2606_p_ce : OUT STD_LOGIC );
    end component;


    component dft_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dft_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072 : component dft_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_start,
        ap_done => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_done,
        ap_idle => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_idle,
        ap_ready => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_ready,
        p_read1 => p_read1,
        sum_r => sum_r_reg_2622,
        sum_i => sum_i_reg_2627,
        p_read2 => p_read2,
        p_read3 => p_read3,
        p_read4 => p_read4,
        p_read5 => p_read5,
        p_read6 => p_read6,
        p_read7 => p_read7,
        p_read8 => p_read8,
        p_read9 => p_read9,
        p_read10 => p_read10,
        p_read11 => p_read11,
        p_read12 => p_read12,
        p_read13 => p_read13,
        p_read14 => p_read14,
        p_read15 => p_read15,
        p_read16 => p_read16,
        p_read17 => p_read17,
        p_read18 => p_read18,
        p_read19 => p_read19,
        p_read20 => p_read20,
        p_read21 => p_read21,
        p_read22 => p_read22,
        p_read23 => p_read23,
        p_read24 => p_read24,
        p_read25 => p_read25,
        p_read26 => p_read26,
        p_read27 => p_read27,
        p_read28 => p_read28,
        p_read29 => p_read29,
        p_read30 => p_read30,
        p_read31 => p_read31,
        p_read32 => p_read32,
        p_read33 => p_read33,
        p_read34 => p_read34,
        p_read35 => p_read35,
        p_read36 => p_read36,
        p_read37 => p_read37,
        p_read38 => p_read38,
        p_read39 => p_read39,
        p_read40 => p_read40,
        p_read41 => p_read41,
        p_read42 => p_read42,
        p_read43 => p_read43,
        p_read44 => p_read44,
        p_read45 => p_read45,
        p_read46 => p_read46,
        p_read47 => p_read47,
        p_read48 => p_read48,
        p_read49 => p_read49,
        p_read50 => p_read50,
        p_read51 => p_read51,
        p_read52 => p_read52,
        p_read53 => p_read53,
        p_read54 => p_read54,
        p_read55 => p_read55,
        p_read56 => p_read56,
        p_read57 => p_read57,
        p_read58 => p_read58,
        p_read59 => p_read59,
        p_read60 => p_read60,
        p_read61 => p_read61,
        p_read62 => p_read62,
        p_read63 => p_read63,
        p_read64 => p_read64,
        p_read65 => p_read65,
        p_read66 => p_read66,
        p_read67 => p_read67,
        p_read68 => p_read68,
        p_read69 => p_read69,
        p_read70 => p_read70,
        p_read71 => p_read71,
        p_read72 => p_read72,
        p_read73 => p_read73,
        p_read74 => p_read74,
        p_read75 => p_read75,
        p_read76 => p_read76,
        p_read77 => p_read77,
        p_read78 => p_read78,
        p_read79 => p_read79,
        p_read80 => p_read80,
        p_read81 => p_read81,
        p_read82 => p_read82,
        p_read83 => p_read83,
        p_read84 => p_read84,
        p_read85 => p_read85,
        p_read86 => p_read86,
        p_read87 => p_read87,
        p_read88 => p_read88,
        p_read89 => p_read89,
        p_read90 => p_read90,
        p_read91 => p_read91,
        p_read92 => p_read92,
        p_read93 => p_read93,
        p_read94 => p_read94,
        p_read95 => p_read95,
        p_read96 => p_read96,
        p_read97 => p_read97,
        p_read98 => p_read98,
        p_read99 => p_read99,
        p_read100 => p_read100,
        p_read101 => p_read101,
        p_read102 => p_read102,
        p_read103 => p_read103,
        p_read104 => p_read104,
        p_read105 => p_read105,
        p_read106 => p_read106,
        p_read107 => p_read107,
        p_read108 => p_read108,
        p_read109 => p_read109,
        p_read110 => p_read110,
        p_read111 => p_read111,
        p_read112 => p_read112,
        p_read113 => p_read113,
        p_read114 => p_read114,
        p_read115 => p_read115,
        p_read116 => p_read116,
        p_read117 => p_read117,
        p_read118 => p_read118,
        p_read119 => p_read119,
        p_read120 => p_read120,
        p_read121 => p_read121,
        p_read122 => p_read122,
        p_read123 => p_read123,
        p_read124 => p_read124,
        p_read125 => p_read125,
        p_read126 => p_read126,
        p_read127 => p_read127,
        p_read128 => p_read128,
        p_read129 => p_read129,
        p_read130 => p_read130,
        p_read131 => p_read131,
        p_read132 => p_read132,
        p_read133 => p_read133,
        p_read134 => p_read134,
        p_read135 => p_read135,
        p_read136 => p_read136,
        p_read137 => p_read137,
        p_read138 => p_read138,
        p_read139 => p_read139,
        p_read140 => p_read140,
        p_read141 => p_read141,
        p_read142 => p_read142,
        p_read143 => p_read143,
        p_read144 => p_read144,
        p_read145 => p_read145,
        p_read146 => p_read146,
        p_read147 => p_read147,
        p_read148 => p_read148,
        p_read149 => p_read149,
        p_read150 => p_read150,
        p_read151 => p_read151,
        p_read152 => p_read152,
        p_read153 => p_read153,
        p_read154 => p_read154,
        p_read155 => p_read155,
        p_read156 => p_read156,
        p_read157 => p_read157,
        p_read158 => p_read158,
        p_read159 => p_read159,
        p_read160 => p_read160,
        p_read161 => p_read161,
        p_read162 => p_read162,
        p_read163 => p_read163,
        p_read164 => p_read164,
        p_read165 => p_read165,
        p_read166 => p_read166,
        p_read167 => p_read167,
        p_read168 => p_read168,
        p_read169 => p_read169,
        p_read170 => p_read170,
        p_read171 => p_read171,
        p_read172 => p_read172,
        p_read173 => p_read173,
        p_read174 => p_read174,
        p_read175 => p_read175,
        p_read176 => p_read176,
        p_read177 => p_read177,
        p_read178 => p_read178,
        p_read179 => p_read179,
        p_read180 => p_read180,
        p_read181 => p_read181,
        p_read182 => p_read182,
        p_read183 => p_read183,
        p_read184 => p_read184,
        p_read185 => p_read185,
        p_read186 => p_read186,
        p_read187 => p_read187,
        p_read188 => p_read188,
        p_read189 => p_read189,
        p_read190 => p_read190,
        p_read191 => p_read191,
        p_read192 => p_read192,
        p_read193 => p_read193,
        p_read194 => p_read194,
        p_read195 => p_read195,
        p_read196 => p_read196,
        p_read197 => p_read197,
        p_read198 => p_read198,
        p_read199 => p_read199,
        p_read200 => p_read200,
        p_read201 => p_read201,
        p_read202 => p_read202,
        p_read203 => p_read203,
        p_read204 => p_read204,
        p_read205 => p_read205,
        p_read206 => p_read206,
        p_read207 => p_read207,
        p_read208 => p_read208,
        p_read209 => p_read209,
        p_read210 => p_read210,
        p_read211 => p_read211,
        p_read212 => p_read212,
        p_read213 => p_read213,
        p_read214 => p_read214,
        p_read215 => p_read215,
        p_read216 => p_read216,
        p_read217 => p_read217,
        p_read218 => p_read218,
        p_read219 => p_read219,
        p_read220 => p_read220,
        p_read221 => p_read221,
        p_read222 => p_read222,
        p_read223 => p_read223,
        p_read224 => p_read224,
        p_read225 => p_read225,
        p_read226 => p_read226,
        p_read227 => p_read227,
        p_read228 => p_read228,
        p_read229 => p_read229,
        p_read230 => p_read230,
        p_read231 => p_read231,
        p_read232 => p_read232,
        p_read233 => p_read233,
        p_read234 => p_read234,
        p_read235 => p_read235,
        p_read236 => p_read236,
        p_read237 => p_read237,
        p_read238 => p_read238,
        p_read239 => p_read239,
        p_read240 => p_read240,
        p_read241 => p_read241,
        p_read242 => p_read242,
        p_read243 => p_read243,
        p_read244 => p_read244,
        p_read245 => p_read245,
        p_read246 => p_read246,
        p_read247 => p_read247,
        p_read248 => p_read248,
        p_read249 => p_read249,
        p_read250 => p_read250,
        p_read251 => p_read251,
        p_read252 => p_read252,
        p_read253 => p_read253,
        p_read254 => p_read254,
        p_read255 => p_read255,
        real_output_address0 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_real_output_address0,
        real_output_ce0 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_real_output_ce0,
        real_output_we0 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_real_output_we0,
        real_output_d0 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_real_output_d0,
        imag_output_address0 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_imag_output_address0,
        imag_output_ce0 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_imag_output_ce0,
        imag_output_we0 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_imag_output_we0,
        imag_output_d0 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_imag_output_d0,
        grp_fu_2596_p_din0 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_din0,
        grp_fu_2596_p_din1 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_din1,
        grp_fu_2596_p_opcode => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_opcode,
        grp_fu_2596_p_dout0 => grp_fu_2596_p2,
        grp_fu_2596_p_ce => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_ce,
        grp_fu_2601_p_din0 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_din0,
        grp_fu_2601_p_din1 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_din1,
        grp_fu_2601_p_opcode => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_opcode,
        grp_fu_2601_p_dout0 => grp_fu_2601_p2,
        grp_fu_2601_p_ce => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_ce,
        grp_fu_2606_p_din0 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2606_p_din0,
        grp_fu_2606_p_din1 => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2606_p_din1,
        grp_fu_2606_p_dout0 => grp_fu_2606_p2,
        grp_fu_2606_p_ce => grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2606_p_ce);

    fadd_32ns_32ns_32_5_full_dsp_1_U1285 : component dft_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2596_p0,
        din1 => grp_fu_2596_p1,
        ce => grp_fu_2596_ce,
        dout => grp_fu_2596_p2);

    fadd_32ns_32ns_32_5_full_dsp_1_U1286 : component dft_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2601_p0,
        din1 => grp_fu_2601_p1,
        ce => grp_fu_2601_ce,
        dout => grp_fu_2601_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U1287 : component dft_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_2606_p0,
        din1 => grp_fu_2606_p1,
        ce => grp_fu_2606_ce,
        dout => grp_fu_2606_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_ready = ap_const_logic_1)) then 
                    grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                mul_i_reg_2617 <= grp_fu_2606_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                sum_i_reg_2627 <= grp_fu_2601_p2;
                sum_r_reg_2622 <= grp_fu_2596_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_done, ap_CS_fsm_state12)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_done)
    begin
        if ((grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_done, ap_CS_fsm_state12)
    begin
        if (((grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_done, ap_CS_fsm_state12)
    begin
        if (((grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_start <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_ap_start_reg;

    grp_fu_2596_ce_assign_proc : process(grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_ce, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_2596_ce <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_ce;
        else 
            grp_fu_2596_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_2596_p0_assign_proc : process(p_read, grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_din0, ap_CS_fsm_state12, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_2596_p0 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_2596_p0 <= p_read;
        else 
            grp_fu_2596_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_2596_p1_assign_proc : process(grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_din1, ap_CS_fsm_state12, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_2596_p1 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2596_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_2596_p1 <= ap_const_lv32_0;
        else 
            grp_fu_2596_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_2601_ce_assign_proc : process(grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_ce, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_2601_ce <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_ce;
        else 
            grp_fu_2601_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_2601_p0_assign_proc : process(mul_i_reg_2617, grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_din0, ap_CS_fsm_state12, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_2601_p0 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_2601_p0 <= mul_i_reg_2617;
        else 
            grp_fu_2601_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_2601_p1_assign_proc : process(grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_din1, ap_CS_fsm_state12, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_2601_p1 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2601_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_2601_p1 <= ap_const_lv32_0;
        else 
            grp_fu_2601_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_2606_ce_assign_proc : process(grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2606_p_ce, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_2606_ce <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2606_p_ce;
        else 
            grp_fu_2606_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_2606_p0_assign_proc : process(p_read, grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2606_p_din0, ap_CS_fsm_state12, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_2606_p0 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2606_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_2606_p0 <= p_read;
        else 
            grp_fu_2606_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_2606_p1_assign_proc : process(grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2606_p_din1, ap_CS_fsm_state12, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_2606_p1 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_grp_fu_2606_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_2606_p1 <= ap_const_lv32_0;
        else 
            grp_fu_2606_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    imag_output_address0 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_imag_output_address0;
    imag_output_ce0 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_imag_output_ce0;
    imag_output_d0 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_imag_output_d0;
    imag_output_we0 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_imag_output_we0;
    real_output_address0 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_real_output_address0;
    real_output_ce0 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_real_output_ce0;
    real_output_d0 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_real_output_d0;
    real_output_we0 <= grp_Loop_VITIS_LOOP_23_2_proc_Pipeline_VITIS_LOOP_23_2_fu_2072_real_output_we0;
end behav;
